// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoGestionInventario.Entities.Entities;

public partial class tbLotes
{
    public int lote_Id { get; set; }

    public int prod_Id { get; set; }

    public int lote_Cantidad { get; set; }

    public DateTime lote_FechaVencimiento { get; set; }

    public int usua_UsuarioCreacion { get; set; }

    public DateTime lote_FechaCreacion { get; set; }

    public int? usua_UsuarioModificacion { get; set; }

    public DateTime? lote_FechaModificacion { get; set; }

    public bool? lote_Estado { get; set; }

    public virtual tbProductos prod { get; set; }

    public virtual ICollection<tbSalidasDetalles> tbSalidasDetalles { get; set; } = new List<tbSalidasDetalles>();

    public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
}