// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoGestionInventario.Entities.Entities;

public partial class tbPantallas
{
    public int pant_Id { get; set; }

    public string pant_Nombre { get; set; }

    public string pant_Url { get; set; }

    public string pant_Identificador { get; set; }

    public string pant_Icono { get; set; }

    public string pant_Componente { get; set; }

    public string pant_PropiedadExtra { get; set; }

    public string pant_PropiedadExtra_1 { get; set; }

    public string pant_PropiedadExtra_2 { get; set; }

    public int usua_UsuarioCreacion { get; set; }

    public DateTime pant_FechaCreacion { get; set; }

    public int? usua_UsuarioModificacion { get; set; }

    public DateTime? pant_FechaModificacion { get; set; }

    public bool? pant_Estado { get; set; }

    public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
}