// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoGestionInventario.Entities.Entities;

public partial class tbProducto
{
    public int prod_Id { get; set; }

    public string prod_Descripcion { get; set; }

    public int? prov_Id { get; set; }

    public int? cate_Id { get; set; }
}