// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoGestionInventario.Entities.Entities;

public partial class tbSalidas
{
    public int sali_Id { get; set; }

    public int usua_Id { get; set; }

    public int sucu_Id { get; set; }

    public string sucu_SalidaEstado { get; set; }

    public int usua_UsuarioCreacion { get; set; }

    public DateTime sali_FechaCreacion { get; set; }

    public int? usua_UsuarioModificacion { get; set; }

    public DateTime? saliFechaModificacion { get; set; }

    public virtual tbSucursales sucu { get; set; }

    public virtual ICollection<tbSalidasDetalles> tbSalidasDetalles { get; set; } = new List<tbSalidasDetalles>();

    public virtual tbUsuarios usua { get; set; }

    public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
}