// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoGestionInventario.Entities.Entities;

public partial class tbSalidasDetalles
{
    public int sade_Id { get; set; }

    public int sali_Id { get; set; }

    public int lote_Id { get; set; }

    public int? sade_Cantidad { get; set; }

    public int usua_UsuarioCreacion { get; set; }

    public DateTime sade_FechaCreacion { get; set; }

    public int? usua_UsuarioModificacion { get; set; }

    public DateTime? sade_FechaModificacion { get; set; }

    public virtual tbLotes lote { get; set; }

    public virtual tbSalidas sali { get; set; }

    public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
}