// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoGestionInventario.Entities.Entities;

public partial class VW_tbSucursales
{
    public int sucu_Id { get; set; }

    public string sucu_Descripcion { get; set; }

    public int usua_UsuarioCreacion { get; set; }

    public string usua_UsuarioCreacion_Nombre { get; set; }

    public DateTime sucu_FechaCreacion { get; set; }

    public int? usua_UsuarioModificacion { get; set; }

    public string usua_UsuarioModificacion_Nombre { get; set; }

    public DateTime? sucu_FechaModificacion { get; set; }

    public bool? sucu_Estado { get; set; }
}