// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoGestionInventario.Entities.Entities;

public partial class VW_tbSalidas
{
    public int sali_Id { get; set; }

    public int sucu_Id { get; set; }

    public DateTime sali_FechaCreacion { get; set; }

    public DateTime? saliFechaModificacion { get; set; }

    public string sucu_SalidaEstado { get; set; }

    public int usua_UsuarioCreacion { get; set; }

    public string usua_UsuarioCreacion_Nombre { get; set; }

    public int? usua_UsuarioModificacion { get; set; }

    public string usua_UsuarioModificacion_Nombre { get; set; }

    public int? Unidades_Totales { get; set; }

    public decimal? costo_Total { get; set; }
}